apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: {{ .Chart.Name }}-{{ .Release.Revision }}
data:
  settings_properties_filename: "settings.properties"
  require_windows_authentication: {{ quote .Values.require_windows_authentication }}
{{ if eq .Values.require_windows_authentication "true" }}
  logging_enabled: "true"
  auditing_enabled: "true"
{{ end }}
{{- range .Values.usertype }}
  user: {{ quote . }}
{{ end }}
{{- range .Values.accesspolicy }}
  accesspolicy: {{ quote . }}
{{ end }}