apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Chart.Name }}-{{ .Release.Revision }}
  namespace:  {{ .Chart.Name }}-{{ .Release.Revision }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
