apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: {{ .Chart.Name }}-{{ .Release.Revision }}
data:
  .secret-file:
---
{{- range .Values.environment }}
apiVersion: v1
kind: Secret
metadata:
  name: secret-serviceaccount-{{ . }}
  annotations:
    kubernetes.io/service-account.name: "sa-{{ . }}"
type: kubernetes.io/service-account-token
data:
  extra: 
{{- end }}
---
{{- range .Values.usertype }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-{{ . }}-secret
type: Opaque
data:
  mysql-{{ . }}-password:
{{- end }}