apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: {{ .Chart.Name }}-{{ .Release.Revision }}
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-app