apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  .secret-file: c2VjcmV0LXZhbHVl
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-serviceaccount-prd
  annotations:
    kubernetes.io/service-account.name: "sa-prd"
type: kubernetes.io/service-account-token
data:
  extra: c2VjcmV0LXNlcnZpY2VhY2NvdW50LXByZAo=   
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-serviceaccount-dev
  annotations:
    kubernetes.io/service-account.name: "sa-dev"
type: kubernetes.io/service-account-token
data:
  extra: c2VjcmV0LXNlcnZpY2VhY2NvdW50LWRldgo=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-developer-secret
type: Opaque
data:
  mysql-developer-password: bXlzcWwtZGV2ZWxvcGVyLXNlY3JldA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-tester-secret
type: Opaque
data:
  mysql-tester-password: bXlzcWwtdGVzdGVyLXNlY3JldA==
